// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

//int sum(int a,int b);
import _ "unsafe"

//export sum
func sum(a,b  /*line :7:14*/_Ctype_int /*line :7:19*/)  /*line :7:21*/_Ctype_int /*line :7:26*/ {
	return a + b
}

func main(){}